{% set name = "python-hookman" %}
{% set version = "0.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 87426b911f723b2ec024c411ed9a5f8a3673b2d4c66600efc84bcda281ccab51

build:
  number: 0
  entry_points:
    - hookman=hookman.__main__:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - attrs
    - click >=7.0
    - invoke
    - python >={{ python_min }}
    - strictyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - hookman
  commands:
    - hookman --help

about:
  home: https://github.com/esss/hookman
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HookMan is a python package that provides a plugin management system to applications, specially those who are written (in totally or partially) in C++.

extra:
  recipe-maintainers:
    - nicoddemus
    - williamjamir
