{% set name = "python-hookman" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f009e6b944af847425121aa147483652c79f26c81ac51da1db0f98811681562

build:
  number: 1
  entry_points:
    - hookman=hookman.__main__:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - attrs
    - click >=7.0
    - invoke
    - python >={{ python_min }}
    - strictyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - hookman
  commands:
    - hookman --help

about:
  home: https://github.com/esss/hookman
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HookMan is a python package that provides a plugin management system to applications, specially those who are written (in totally or partially) in C++.

extra:
  recipe-maintainers:
    - nicoddemus
    - williamjamir
