travis:
  secure:
    BINSTAR_TOKEN: NJXtYymRNJG27EPa34gQucVSz/DI3dEzl2iTuwRBruPJ9OZ08uev/lewNCZeO1J95SeeeTltJY3WmIOpPr7Ed7GEelqmNPLOIL8toPkTjUMEix5ed4c7Eu6EM0f8E+3nNtD/nvc5PB6iGWOnC8kPnLdxGQ4B4AQRawt0EpJHeKRqJ+YIzlzeyIy5k8llEnnJd0kfBa0+aObl6saQ9O++X43iHZdPTjT+ZRbtJKE4hO4jF6EX5xkGwxDDVql+l/lBRCSmd3e04aqIOp2LB9MvTA4jUIGsghsjk2RNbcPvU/dlANrHrH3sacpRCpv6h9RStArww6tHR4+LTthX91CF/NiETCkHYJGViFD+MFYMsERmmjls7+VTHbckGk5MjZccPNulQ56UIUpoWBLoqf2N3SgSke0KszxyrVxA73iYYqCsjVDhjAr8aorJJaTLWzwtGte2FWhMv7afaPpaF4hpS6zMh8K4ekN2zUsuiVHspWhxWEMLx4LIv1gNNHaLj915DYVm90uVkWHwyF0gMi30Z3pNDRKzwZLMZaURHe+4agt/thfdaJX3TPpr1OGIND3ujKpN6qSzE1KuL7TalZ3e1g2ht/KjftL26k+tvydYrQ8lJKApdLTFBXjTwu5FJ8VWtZYR80q+x3wSP2SRAj4FlTXsV37tMZPFCztnfrG09RE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
